apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
bases:
  - ../base
  # github.com/utilitywarehouse/vault-manifests//base?ref=1.2.3-1
patchesStrategicMerge:
  - vault-patch.yaml
secretGenerator:
  - name: vault-tls
    type: kubernetes.io/tls
    files:
      - tls.crt=secrets/vault-tls.crt
      - tls.key=secrets/vault-tls.key
      - ca.crt=secrets/vault-ca.crt
resources:
  - vault-cluster-role-binding.yaml
  - vault-namespaced-role-binding.yaml
