apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
bases:
  - ../base
  # github.com/utilitywarehouse/vault-manifests//base?ref=1.2.3-1
patchesStrategicMerge:
  - vault-patch.yaml
  - vault-pki-patch.yaml
resources:
  - vault-client-namespace-role-binding.yaml
  - vault-cluster-role-binding.yaml
  - vault-namespaced-role-binding.yaml
