# Used by vault pki to provide CA to client namespaces
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: vault-configmap-applier
rules:
- apiGroups: [""]
  resources: ["configmaps"]
  verbs: ["create", "update", "patch"]
---
kind: RoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: vault-configmap-applier
roleRef:
  kind: Role
  name: vault-configmap-applier
  apiGroup: rbac.authorization.k8s.io
subjects:
  - kind: ServiceAccount
    name: vault-pki
    # Placeholder, patch with the vault namespace value
    namespace: example
