apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
bases:
  - ../../base
  # github.com/utilitywarehouse/vault-manifests//base?ref=1.2.0-1
patchesStrategicMerge:
  - vault-patch.yaml
secretGenerator:
  - name: vault-secrets
    type: Opaque
    files:
      - aws-secret-access-key=secrets/vault-aws-secret-access-key
  - name: vault-tls
    type: kubernetes.io/tls
    files:
      - tls.crt=secrets/vault-tls.crt
      - tls.key=secrets/vault-tls.key
configMapGenerator:
  - name: vault
    files:
      - config.hcl=resources/vault-config.hcl
resources:
  - vault-cluster-role-binding.yaml
