apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: vault
  # startup logs are sensitive, so you may want to exclude them from
  # your logging pipeline
  annotations:
    fluentbit.io/exclude: "true"
spec:
  template:
    spec:
      containers:
        - name: unsealer
          env:
            - name: UNSEAL_KEY
              valueFrom:
                secretKeyRef:
                  name: vault-unseal
                  key: unseal-key
        - name: vault
          env:
            - name: AWS_ACCESS_KEY_ID
              value: XXXXXXXXXXXXXXXXXXXX
            - name: AWS_SECRET_ACCESS_KEY
              valueFrom:
                secretKeyRef:
                  name: vault-aws
                  key: aws-secret-access-key
