apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ca-server.yaml
  - rbac.yaml
  - vault.yaml
  - vault-pki.yaml
configMapGenerator:
  - name: statsd-mappings
    files:
      - resources/statsd-mappings.yaml
images:
  - name: quay.io/utilitywarehouse/vault-toolkit
    newTag: master
