apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ca-server.yaml
  - cert.yaml
  - rbac.yaml
  - vault.yaml
images:
  - name: quay.io/utilitywarehouse/vault-toolkit
    newTag: master
