apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - rbac.yaml
  - vault.yaml
  - vault-pki.yaml
configMapGenerator:
  - name: nginx-config
    files:
      - resources/nginx.conf
images:
  - name: quay.io/utilitywarehouse/vault-manifests
    newTag: 1.3.2-1
