apiVersion: v1
kind: Secret
metadata:
  name: vault-tls
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: vault-pki
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: vault-pki
spec:
  selector:
    matchLabels:
      app: vault-pki
  template:
    metadata:
      labels:
        app: vault-pki
    spec:
      serviceAccountName: vault-pki
      containers:
        - name: pki-manager
          image: quay.io/utilitywarehouse/vault-pki-manager:0.1.0
          env:
            - name: VAULT_NAMESPACE
              valueFrom:
                fieldRef:
                  fieldPath: metadata.namespace
          volumeMounts:
            - name: tls
              mountPath: /etc/tls
      volumes:
        - name: tls
          secret:
            secretName: vault-tls
            optional: true
