apiVersion: v1
kind: ServiceAccount
metadata:
  name: vault
---
# Placeholder to be patched by the initializer
apiVersion: v1
kind: Secret
metadata:
  name: vault
---
# For use by vault clients
apiVersion: v1
kind: Service
metadata:
  name: vault
  labels:
    app: vault
spec:
  selector:
    app: vault
  ports:
    - port: 8200
      name: public-api
---
# For internal cluster member communication
apiVersion: v1
kind: Service
metadata:
  name: vault-cluster
  labels:
    app: vault
spec:
  publishNotReadyAddresses: true
  clusterIP: None
  selector:
    app: vault
  ports:
    - port: 8200
      name: public-api
    - port: 8201
      name: members-internal-api
---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: vault
spec:
  serviceName: vault
  replicas: 3
  selector:
    matchLabels:
      app: vault
  template:
    metadata:
      labels:
        app: vault
      annotations:
        prometheus.io/scrape: "true"
        prometheus.io/path: /__/metrics
        prometheus.io/port: "8080"
    spec:
      serviceAccountName: vault
      shareProcessNamespace: true
      affinity:
        podAntiAffinity:
          preferredDuringSchedulingIgnoredDuringExecution:
            - podAffinityTerm:
                labelSelector:
                  matchExpressions:
                    - key: app
                      operator: In
                      values:
                        - vault
                topologyKey: failure-domain.beta.kubernetes.io/zone
              weight: 100
      initContainers:
        # Install ca cert as a root CA
        - name: ca
          image: alpine
          command:
            - sh
            - -c
            - |
              set -e
              apk add --update ca-certificates
              cp /etc/tls/ca.crt /usr/local/share/ca-certificates/vault-ca.crt
              update-ca-certificates
              cp /etc/ssl/certs/* /ssl-certs
          volumeMounts:
            - name: tls
              mountPath: /etc/tls
            - name: ssl-certs
              mountPath: /ssl-certs
        # Write vault config to file
        - name: vault-config
          image: alpine
          command:
            - sh
            - -c
            - echo "$VAULT_CONFIG" > /vault/config/config.hcl
          env:
            - name: POD_NAME
              valueFrom:
                fieldRef:
                  fieldPath: metadata.name
            - name: POD_NAMESPACE
              valueFrom:
                fieldRef:
                  fieldPath: metadata.namespace
            - name: VAULT_CONFIG
              value: |
                listener "tcp" {
                  address         = "0.0.0.0:8200"
                  cluster_address = "0.0.0.0:8201"
                  tls_key_file    = "/etc/tls/tls.key"
                  tls_cert_file   = "/etc/tls/tls.crt"
                  telemetry {
                    unauthenticated_metrics_access = true
                  }
                }

                storage "raft" {
                  path    = "/vault/storage"
                  node_id = "$(POD_NAME)"
                }

                telemetry {
                  prometheus_retention_time = "90s",
                  disable_hostname = true
                }

                api_addr      = "https://$(POD_NAME).vault.$(POD_NAMESPACE):8200"
                cluster_addr  = "https://$(POD_NAME).vault-cluster.$(POD_NAMESPACE):8201"
                disable_mlock = true
          volumeMounts:
            - name: vault-config
              mountPath: /vault/config
      containers:
        - name: initializer
          image: alpine
          command:
            - /bin/sh
            - -c
            - |
              # Only run the initializer in the first replica
              replica="${HOSTNAME: -1}";
              if [ "${replica}" != "0" ];then
                echo "this replica is not responsible for initialization, going to sleep";
                while true; do sleep 86400; done
              fi

              # Validations and defaults
              : ${VAULT_CACERT:?"Need to set VAULT_CACERT"};
              apk -q add curl jq;
              vault_name="${VAULT_ADDR:-"vault"}";
              kubectl_version="${KUBECTL_VERSION:-"$(curl -s https://storage.googleapis.com/kubernetes-release/release/stable.txt)"}";
              leader_addr="https://${vault_name}-0.${vault_name}-cluster:8200";
              replicas="${VAULT_REPLICAS:-"3"}";

              # Wait until vault answers the initialization check
              until [ "${initialized}" = "true" -o "${initialized}" = "false" ]; do
                initialized=$(curl -s --cacert "${VAULT_CACERT}" "${leader_addr}/v1/sys/init" | jq '.initialized');
                echo 'leader not ready, sleeping for 3 seconds';
                sleep 3;
              done;

              if [ "${initialized}" = "true" ];then
                echo "vault is already initialized, going to sleep";
                while true; do sleep 86400; done
              fi

              # Install kubectl
              curl -sLO "https://storage.googleapis.com/kubernetes-release/release/${kubectl_version}/bin/linux/amd64/kubectl";
              chmod +x ./kubectl;
              mv ./kubectl /usr/local/bin;

              # Initialize vault and update secret
              init=$(curl -s --cacert "${VAULT_CACERT}" "${leader_addr}/v1/sys/init" \
                -XPUT -d '{"secret_shares":1,"secret_threshold": 1}');
              token=$(echo "${init}" | jq -r '.root_token');
              unseal_key=$(echo "${init}" | jq -r '.keys[0]');
              kubectl patch secret vault -p '{"stringData":{"unseal-key":"'"${unseal_key}"'","root-token":"'"${token}"'"}}'
              echo "vault initialized"

              # Unseal leader
              curl -s --cacert "${VAULT_CACERT}" "${leader_addr}/v1/sys/unseal" -XPUT -d '{"key":"'"${unseal_key}"'"}'
              echo "leader unsealed"

              # Wait for replicas api and join and unseal them
              join_replica()
              {
                replica_number="$1";
                replica_name="${vault_name}-${replica_number}";
                replica_addr="https://${replica_name}.${vault_name}-cluster:8200";
                until curl -s --cacert "${VAULT_CACERT}" "${replica_addr}/v1/sys/init"; do
                  echo "${replica_name} not ready, sleeping for 3 seconds";
                  sleep 3;
                done;

                curl -s --cacert "${VAULT_CACERT}" "${replica_addr}/v1/sys/storage/raft/join" -XPUT -d '{"leader_api_addr":"'"${leader_addr}"'"}'
                curl -s --cacert "${VAULT_CACERT}" "${replica_addr}/v1/sys/unseal" -XPUT -d '{"key":"'"${unseal_key}"'"}'
                echo "${replica_name} joined and initialized"
              }
              for i in $(seq $(($replicas - 1))) ; do
                join_replica $i;
              done
          env:
            - name: VAULT_CACERT
              value: "/etc/tls/ca.crt"
          volumeMounts:
            - name: tls
              mountPath: /etc/tls
        - name: unsealer
          image: alpine
          command:
            - /bin/sh
            - -c
            - |
              set -e

              vault_addr="${VAULT_ADDR:-"https://127.0.0.1:8200"}";

              # Sleep if no unseal key provided
              if [ -z "${UNSEAL_KEY}" ]; then
                echo "No unseal key provided, going to sleep";
                while true; do sleep 86400; done
              fi

              apk -q add curl jq;

              # Wait for vault api and sleep if not initialized
              until [ "${initialized}" = "true" -o "${initialized}" = "false" ]; do
                initialized=$(curl -s --cacert "${VAULT_CACERT}" "${vault_addr}/v1/sys/init" | jq '.initialized');
                echo 'leader not ready, sleeping for 3 seconds';
                sleep 3;
              done;

              if [ "${initialized}" = "false" ];then
                echo "vault is not initialized, going to sleep";
                while true; do sleep 86400; done
              fi

              # Unseal and sleep
              echo 'Attempting to unseal vault'
              curl -s --cacert "${VAULT_CACERT}" "${vault_addr}/v1/sys/unseal" \
                -XPUT -d '{"key":"'"${UNSEAL_KEY}"'"}' \
                | jq .sealed \
                | grep -q "^false$";
              echo "vault unsealed, going to sleep";
              while true; do sleep 86400; done
          env:
            - name: VAULT_CACERT
              value: "/etc/tls/ca.crt"
            - name: UNSEAL_KEY
              valueFrom:
                secretKeyRef:
                  name: vault
                  key: unseal-key
                  optional: true
          volumeMounts:
            - name: tls
              mountPath: /etc/tls
        - name: vault
          image: vault:1.3.2
          livenessProbe:
            # Alive if Vault is uninitialized or unsealed and active/standby
            httpGet:
              path: /v1/sys/health?standbyok=true&uninitcode=204
              port: 8200
              scheme: HTTPS
            initialDelaySeconds: 30
            periodSeconds: 10
          readinessProbe:
            # Ready if Vault is initialized, unsealed and active/standby
            httpGet:
              path: /v1/sys/health?standbyok=true
              port: 8200
              scheme: HTTPS
            initialDelaySeconds: 10
            periodSeconds: 10
          command:
            - /usr/bin/dumb-init
            - --
            - vault
            - server
            - -config=/vault/config
          ports:
            - containerPort: 8200
            - containerPort: 8201
          volumeMounts:
            - name: vault-config
              mountPath: /vault/config
            - name: storage
              mountPath: /vault/storage
            - name: tls
              mountPath: /etc/tls
            - name: ssl-certs
              mountPath: /etc/ssl/certs
          securityContext:
            runAsNonRoot: true
            runAsUser: 1000
            runAsGroup: 100
            allowPrivilegeEscalation: false
        - name: metrics
          image: nginx:alpine
          ports:
            - containerPort: 80
          volumeMounts:
            - name: nginx-config
              mountPath: /etc/nginx/conf.d
        - name: reloader
          image: alpine
          securityContext:
            capabilities:
              add:
                - SYS_PTRACE
          command:
            - /bin/sh
            - -c
            - |
              echo '#!/bin/sh
              if [ "$#" -eq 3 ] && [ "$3" == "..data" ]; then
                  echo "[" $(date -uIseconds) "] config seems to have changed, reloading ..."
                  vault_pid=$(pgrep vault)
                  kill -HUP "${vault_pid}"
              fi' > /reload && chmod +x /reload && inotifyd /reload /etc/tls:y
          volumeMounts:
            - name: tls
              mountPath: /etc/tls
      securityContext:
        fsGroup: 1000
      volumes:
        - name: tls
          secret:
            secretName: vault-tls
            defaultMode: 0400
        - name: vault-config
          emptyDir: {}
        - name: nginx-config
          configMap:
            name: nginx-config
        - name: ssl-certs
          emptyDir: {}
  volumeClaimTemplates:
    - metadata:
        name: storage
      spec:
        accessModes:
          - ReadWriteOnce
        resources:
          requests:
            storage: 1Gi
