apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: vault-pki
rules:
  - apiGroups:
      - ""
    resources:
      - configmaps
    verbs:
      - "create"
      - "get"
      - "patch"
      - "update"
  - apiGroups:
      - ""
    resources:
      - namespaces
    verbs:
      - "get"
      - "list"
      - "watch"
