apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
bases:
  - ../../base/vault-namespace
  # github.com/utilitywarehouse/vault-manifests//base/vault-namespace?ref=1.7.1-1
resources:
  - rbac.yaml
