kind: RoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: vault-secret-applier
roleRef:
  kind: Role
  name: vault-secret-applier
  apiGroup: rbac.authorization.k8s.io
subjects:
  - kind: ServiceAccount
    name: vault
    # Placeholder, patch with the vault namespace value
    namespace: example
  - kind: ServiceAccount
    name: vault-pki
    # Placeholder, patch with the vault namespace value
    namespace: example
---
kind: RoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: vault-pod-deleter
roleRef:
  kind: Role
  name: vault-pod-deleter
  apiGroup: rbac.authorization.k8s.io
subjects:
  - kind: ServiceAccount
    name: vault
    # Placeholder, patch with the vault namespace value
    namespace: example
